name: estate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_ui_auth: ^1.15.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  logger: ^2.4.0
  cloud_firestore: ^5.4.2
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  firebase_storage: ^12.3.1
  form_builder_image_picker: ^4.1.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  location: ^6.0.2
  latlong2: ^0.9.1
  gap: ^3.0.1
  refena_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
